baseURL = "https://eckelon.net"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "/var/blog/jasamitier"
theme = "anubis"
paginate = 5

disqusShortname = ""
googleAnalytics = ""

[author]
name = "JA Samitier"

[params]
author = "JA Samitier"
description = "Welcome to eckelon.net"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "light-without-switcher"
readMore = true
customCSS = ["css/my.css"]

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "twitter"
url = "https://twitter.com/eckelon"
[[params.social]]
id = "linkedin"
url = "https://linkedin.com/in/jasamitier"

[menu]

[[menu.main]]
identifier = "about"
name = "About me"
url = "/about/"
weight = 1

# [[menu.main]]
# identifier = "tags"
# name = "Tags"
# url = "/tags/"
# weight = 2

# [[menu.main]]
# name = "Archive"
# identifier = "archive"
# url = "/blog/"
# weight = 3

[languages.en]
languageName = "English"
[languages.es]
languageName = "Español"
description = "Bienvenido a eckelon.net"

[[languages.es.menu.main]]
identifier = "about"
name = "Sobre mi"
url = "/about/"
weight = 1

# [[languages.es.menu.main]]
# identifier = "tags"
# name = "Etiquetas"
# url = "/tags/"
# weight = 2

# [[languages.es.menu.main]]
# identifier = "archive"
# name = "Archivos"
# url = "/blog/"
# weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
